/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JFrame;

/**
 *
 * @author LukaSkywallker
 */
public class HangmanPanel extends javax.swing.JPanel {
    private int brojPogresnihPokusaja;

    public HangmanPanel(int brojPogresnihPokusaja) {
        this.brojPogresnihPokusaja = brojPogresnihPokusaja;
    }
    /**
     * Creates new form HangmanPanel
     */
    public HangmanPanel() {
        initComponents();
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Crtanje vesala
        g.setColor(Color.BLACK);
        g.fillRect(40, 40, 10, 210); // Vertikalna linija
        g.fillRect(40, 40, 90, 10); // Horizontalna linija
        g.fillRect(120, 40, 3, 60); // Linija za vrat
        g.fillRect(85, 100, 70, 3); // Linija za gornji deo tela

        // Crtanje delova tela u zavisnosti od broja pogresnih pokusaja
        if (brojPogresnihPokusaja >= 1)
            g.drawOval(115, 100, 50, 50); // glava
        if (brojPogresnihPokusaja >= 2)
            g.drawLine(140, 150, 140, 230); // telo
        if (brojPogresnihPokusaja >= 3)
            g.drawLine(140, 160, 100, 190); // leva ruka
        if (brojPogresnihPokusaja >= 4)
            g.drawLine(140, 160, 180, 190); // desna ruka
        if (brojPogresnihPokusaja >= 5)
            g.drawLine(140, 230, 100, 260); // leva noga
        if (brojPogresnihPokusaja >= 6)
            g.drawLine(140, 230, 180, 260); // desna noga
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(250, 300);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Hangman Panel");
        HangmanPanel panel = new HangmanPanel(6); // Promeni ovde brojPogresnihPokusaja po potrebi
        frame.add(panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
